In [7]:
import requests
import pandas as pd

API_KEY = "1737999817f569a2a861f2b78bfb0230"

cities = ["Delhi", "Mumbai", "Bangalore", "Kolkata", "Chandigarh"]

weather_data = []

for city in cities:
    url = f"http://api.openweathermap.org/data/2.5/weather?q={city}&appid={API_KEY}&units=metric"
    response = requests.get(url).json()
    
    weather_data.append({
        "city": city,
        "temperature": response["main"]["temp"],
        "humidity": response["main"]["humidity"],
        "wind_speed": response["wind"]["speed"],
        "pressure": response["main"]["pressure"]
    })

weather_df = pd.DataFrame(weather_data)
weather_df

         city  temperature  humidity  wind_speed  pressure
0       Delhi        32.05        31        3.09      1008
1      Mumbai        30.99        58        6.17      1010
2   Bangalore        32.61        37        2.68      1008
3     Kolkata        36.97        41        2.57      1004
4  Chandigarh        31.88        21        2.01      1008

In [10]:
token = "2bdc570ded4c9b6812386494e9f86c25775324ce"

aqi_data = []

for city in cities:
    url = f"https://api.waqi.info/feed/{city}/?token={token}"
    response = requests.get(url).json()
    
    data = response["data"]
    
    aqi_data.append({
        "city": city,
        "aqi": data["aqi"],
        "pm25": data["iaqi"]["pm25"]["v"] if "pm25" in data["iaqi"] else None,
        "pm10": data["iaqi"]["pm10"]["v"] if "pm10" in data["iaqi"] else None
    })

aqi_df = pd.DataFrame(aqi_data)
aqi_df

         city  aqi  pm25  pm10
0       Delhi  172   117   172
1      Mumbai  151   151    85
2   Bangalore  114   114    63
3     Kolkata  136   136    20
4  Chandigarh   68    65    68

In [ ]:
from datetime import datetime
import os
df = pd.merge(weather_df , aqi_df , on= "city")
df["timestamp"] = datetime.now().strftime("%H : %M")
df
# os.makedirs("Data/raw", exist_ok=True)
# path_of_data = ("Data/raw.csv")
df.to_csv("Data/raw/raw_data.csv",index=False)