In [33]:
import requests
import pandas as pd
from dotenv import load_dotenv
import os
load_dotenv()
API_KEY = os.getenv("API_KEY")

cities = ["Delhi", "Mumbai", "Bangalore", "Kolkata", "Tokyo","Haryana"]

weather_data = []

for city in cities:
    url = f"http://api.openweathermap.org/data/2.5/weather?q={city}&appid={API_KEY}&units=metric"
    response = requests.get(url).json()
    
    weather_data.append({
        "city": city,
        "temperature": response["main"]["temp"],
        "humidity": response["main"]["humidity"],
        "wind_speed": response["wind"]["speed"],
        "pressure": response["main"]["pressure"]
    })

weather_df = pd.DataFrame(weather_data)
weather_df
# print(weather_df.info())
# print(weather_df.describe())

        city  temperature  humidity  wind_speed  pressure
0      Delhi        26.05        61        3.60      1012
1     Mumbai        30.99        51        3.09      1013
2  Bangalore        28.98        60        3.09      1012
3    Kolkata        33.97        52        3.09      1007
4      Tokyo        14.08        91        5.14      1013
5    Haryana        26.84        41        2.36      1011

In [30]:
token = os.getenv("TOKEN")
aqi_data = []

for city in cities:
    url = f"https://api.waqi.info/feed/{city}/?token={token}"
    response = requests.get(url).json()
    
    if response["status"] == "ok":
        data = response["data"]

        aqi_data.append({
            "city": city,
            "aqi": data["aqi"],
            "pm25": data["iaqi"]["pm25"]["v"] if "pm25" in data["iaqi"] else None,
            "pm10": data["iaqi"]["pm10"]["v"] if "pm10" in data["iaqi"] else None
        })
    
    else:
        print(f"Error for {city}: {response['data']}")

aqi_df = pd.DataFrame(aqi_data)
aqi_df

Error for Haryana: Unknown station

        city  aqi  pm25  pm10
0      Delhi  153   153   101
1     Mumbai   74    74    48
2  Bangalore  109   109    61
3    Kolkata   89    89    40
4      Tokyo   57    57    17

In [31]:
from datetime import datetime

df = pd.merge(weather_df, aqi_df, on="city")
df["timestamp"] = datetime.now().strftime("%H:%M")

df.to_csv(r"D:\PROJECTS\Air_Watch\Data\raw.csv", index=False)
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   city         5 non-null      object
 1   temperature  5 non-null      float64
 2   humidity     5 non-null      int64
 3   wind_speed   5 non-null      float64
 4   pressure     5 non-null      int64
 5   aqi          5 non-null      int64
 6   pm25         5 non-null      int64
 7   pm10         5 non-null      int64
 8   timestamp    5 non-null      object
dtypes: float64(2), int64(5), object(2)
memory usage: 492.0+ bytes
None